#! /usr/bin/env bash

function usage {
    echo Usage: `basename $0` filename
    exit 1
}

if [ $# -eq 1 ]; then
    echo "extract tar archve : tar zxvf ${1}"
    tar zxvf ${1}
else
    usage
fi
exit 0

